name: test2
channels:
  - pytorch
  - anaconda
  - huggingface
  - conda-forge
  - nvidia
  - defaults
dependencies:
  - abseil-cpp=20211102.0
  - aiohttp=3.8.5
  - aiosignal=1.2.0
  - arrow-cpp=11.0.0
  - asttokens=2.0.5
  - async-timeout=4.0.2
  - attrs=23.1.0
  - aws-c-common=0.6.8
  - aws-c-event-stream=0.1.6
  - aws-checksums=0.1.11
  - aws-sdk-cpp=1.8.185
  - backcall=0.2.0
  - blas=1.0
  - boost-cpp=1.82.0
  - bottleneck=1.3.5
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - c-ares=1.19.1
  - ca-certificates=2023.12.12
  - certifi=2024.2.2
  - cffi=1.15.1
  - charset-normalizer=2.0.4
  - click=8.1.7
  - colorama=0.4.6
  - comm=0.1.2
  - cryptography=41.0.3
  - cuda-cccl=12.3.52
  - cuda-cudart=12.1.105
  - cuda-cudart-dev=12.1.105
  - cuda-cupti=12.1.105
  - cuda-libraries=12.1.0
  - cuda-libraries-dev=12.1.0
  - cuda-nvrtc=12.1.105
  - cuda-nvrtc-dev=12.1.105
  - cuda-nvtx=12.1.105
  - cuda-opencl=12.3.52
  - cuda-opencl-dev=12.3.52
  - cuda-profiler-api=12.3.52
  - cuda-runtime=12.1.0
  - cudatoolkit=11.8.0
  - dataclasses=0.8
  - datasets=2.14.7
  - debugpy=1.6.7
  - decorator=5.1.1
  - dill=0.3.7
  - exceptiongroup=1.2.0
  - executing=0.8.3
  - faiss=1.7.4
  - faiss-gpu=1.7.4
  - fastapi=0.103.2
  - filelock=3.9.0
  - freetype=2.12.1
  - frozenlist=1.4.0
  - fsspec=2023.9.2
  - gflags=2.2.2
  - giflib=5.2.1
  - glog=0.5.0
  - grpc-cpp=1.48.2
  - h11=0.14.0
  - huggingface_hub=0.20.2
  - icc_rt=2022.1.0
  - idna=3.4
  - importlib-metadata=6.0.0
  - importlib_metadata=6.0.0
  - intel-openmp=2023.1.0
  - ipykernel=6.25.0
  - ipython=8.15.0
  - jedi=0.18.1
  - jinja2=3.1.2
  - joblib=1.2.0
  - jpeg=9e
  - jupyter_client=8.6.0
  - jupyter_core=5.5.0
  - lerc=3.0
  - libblas=3.9.0
  - libboost=1.82.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcublas=12.1.0.26
  - libcublas-dev=12.1.0.26
  - libcufft=11.0.2.4
  - libcufft-dev=11.0.2.4
  - libcurand=10.3.4.52
  - libcurand-dev=10.3.4.52
  - libcurl=8.1.1
  - libcusolver=11.4.4.55
  - libcusolver-dev=11.4.4.55
  - libcusparse=12.0.2.55
  - libcusparse-dev=12.0.2.55
  - libdeflate=1.17
  - libevent=2.1.12
  - libfaiss=1.7.4
  - libfaiss-avx2=1.7.4
  - libffi=3.4.4
  - libjpeg-turbo=2.0.0
  - liblapack=3.9.0
  - libnpp=12.0.2.50
  - libnpp-dev=12.0.2.50
  - libnvjitlink=12.1.105
  - libnvjitlink-dev=12.1.105
  - libnvjpeg=12.1.1.14
  - libnvjpeg-dev=12.1.1.14
  - libpng=1.6.39
  - libprotobuf=3.20.3
  - libsodium=1.0.18
  - libssh2=1.10.0
  - libthrift=0.15.0
  - libtiff=4.5.1
  - libuv=1.44.2
  - libwebp=1.3.2
  - libwebp-base=1.3.2
  - lz4-c=1.9.4
  - m2w64-gcc-libgfortran=5.3.0
  - m2w64-gcc-libs=5.3.0
  - m2w64-gcc-libs-core=5.3.0
  - m2w64-gmp=6.1.0
  - m2w64-libwinpthread-git=5.0.0.4634.697f757
  - markupsafe=2.1.1
  - matplotlib-inline=0.1.6
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.8
  - mkl_random=1.2.4
  - mpmath=1.3.0
  - msys2-conda-epoch=20160418
  - multidict=6.0.2
  - multiprocess=0.70.15
  - nest-asyncio=1.5.6
  - networkx=3.1
  - nltk=3.8.1
  - numexpr=2.8.7
  - numpy=1.26.0
  - numpy-base=1.26.0
  - openjpeg=2.4.0
  - openssl=3.0.13
  - orc=1.7.4
  - packaging=23.1
  - pandas=2.1.1
  - parso=0.8.3
  - pickleshare=0.7.5
  - pillow=10.0.1
  - pip=23.3
  - platformdirs=3.10.0
  - prompt-toolkit=3.0.36
  - psutil=5.9.0
  - pure_eval=0.2.2
  - pyarrow=11.0.0
  - pyarrow-hotfix=0.5
  - pycparser=2.21
  - pygments=2.15.1
  - pyopenssl=23.2.0
  - pysocks=1.7.1
  - python=3.11.5
  - python-dateutil=2.8.2
  - python-tzdata=2023.3
  - python-xxhash=2.0.2
  - python_abi=3.11
  - pytorch=2.1.1
  - pytorch-cuda=12.1
  - pytorch-mutex=1.0
  - pytz=2023.3.post1
  - pywin32=305
  - pyyaml=6.0.1
  - pyzmq=25.1.0
  - re2=2022.04.01
  - regex=2023.10.3
  - requests=2.31.0
  - sacremoses=0.0.43
  - scikit-learn=1.2.2
  - scipy=1.11.3
  - sentence-transformers=2.3.0
  - sentencepiece=0.1.99
  - setuptools=68.0.0
  - six=1.16.0
  - snappy=1.1.9
  - sniffio=1.3.0
  - sqlite=3.41.2
  - stack_data=0.2.0
  - starlette=0.27.0
  - sympy=1.11.1
  - tbb=2021.8.0
  - threadpoolctl=2.2.0
  - tk=8.6.12
  - tokenizers=0.15.1
  - tornado=6.3.3
  - tqdm=4.65.0
  - traitlets=5.7.1
  - typing-extensions=4.7.1
  - typing_extensions=4.7.1
  - tzdata=2023c
  - ucrt=10.0.22621.0
  - urllib3=1.26.18
  - utf8proc=2.6.1
  - uvicorn=0.27.0.post1
  - vc=14.2
  - vc14_runtime=14.36.32532
  - vs2015_runtime=14.36.32532
  - wcwidth=0.2.5
  - wheel=0.41.2
  - win_inet_pton=1.1.0
  - xxhash=0.8.0
  - xz=5.4.2
  - yaml=0.2.5
  - yarl=1.8.1
  - zeromq=4.3.4
  - zipp=3.11.0
  - zlib=1.2.13
  - zstd=1.5.5
  - pip:
    - annotated-types==0.6.0
    - anyio==4.2.0
    - beautifulsoup4==4.12.2
    - bs4==0.0.1
    - distro==1.9.0
    - docopt==0.6.2
    - elastic-transport==8.12.0
    - elasticsearch==8.12.0
    - gdown==4.7.3
    - httpcore==1.0.2
    - httpx==0.26.0
    - openai==0.28.0
    - pydantic==2.5.3
    - pydantic-core==2.14.6
    - pypdf2==3.0.1
    - python-dotenv==1.0.1
    - safetensors==0.4.2
    - soupsieve==2.5
    - torchaudio==2.1.1
    - torchvision==0.16.1
    - transformers==4.37.2
